import type { Finding } from "../../drizzle/schema";
import { invokeLLM } from "../_core/llm";

export interface ReportMetadata {
  title: string;
  severity: string;
  cvssScore: number;
  cweId?: string;
  affectedAssets: string[];
  discoveredDate: Date;
  reportedDate: Date;
}

/**
 * Generate HackerOne formatted report
 */
export async function generateHackerOneReport(finding: Finding, evidence: string[]): Promise<string> {
  const severity = finding.severity || "high";
  const cvssScore = parseFloat(finding.cvssScore || "0");

  const report = `# Vulnerability Report

## Summary
**Title:** ${finding.title}
**Severity:** ${severity.toUpperCase()}
**CVSS Score:** ${cvssScore}/10

## Description
${finding.description || "No description provided"}

## Impact
${finding.impactStatement || "This vulnerability could allow unauthorized access or data manipulation."}

## Reproduction Steps
${finding.reproductionSteps || `
1. Navigate to ${finding.affectedAssets?.[0] || "the affected endpoint"}
2. Perform the following action...
3. Observe the vulnerability
`}

## Proof of Concept
${evidence.join("\n\n") || "Evidence not available"}

## Affected Assets
${finding.affectedAssets?.map((asset) => `- ${asset}`).join("\n") || "- Unknown"}

## Remediation
Please refer to the OWASP guidelines for fixing ${finding.findingType} vulnerabilities.

## Timeline
- **Discovered:** ${finding.createdAt?.toISOString() || "Unknown"}
- **Reported:** ${new Date().toISOString()}

---
Report generated by ScopeHunter`;

  return report;
}

/**
 * Generate Bugcrowd formatted report
 */
export async function generateBugcrowdReport(finding: Finding, evidence: string[]): Promise<string> {
  const severityMap: Record<string, string> = {
    critical: "P1 - Critical",
    high: "P2 - High",
    medium: "P3 - Medium",
    low: "P4 - Low",
    info: "P5 - Informational",
  };

  const priority = severityMap[finding.severity || "high"] || "P3 - Medium";

  const report = `# ${finding.title}

**Priority:** ${priority}
**Vulnerability Type:** ${finding.findingType}
**CVSS v3.1 Score:** ${finding.cvssScore || "N/A"}

## Vulnerability Description
${finding.description || "No description provided"}

## Business Impact
${finding.impactStatement || "This vulnerability could impact the security of the application and its users."}

## Steps to Reproduce
${finding.reproductionSteps || `
1. Access the affected endpoint: ${finding.affectedAssets?.[0] || "Unknown"}
2. Perform the following actions...
3. Observe the vulnerability
`}

## Proof of Concept
${evidence.join("\n\n") || "Evidence not available"}

## Affected Endpoints/Assets
${finding.affectedAssets?.map((asset) => `- ${asset}`).join("\n") || "- Unknown"}

## Suggested Fix
Implement proper input validation and output encoding to prevent ${finding.findingType} vulnerabilities.

## References
- CWE: ${finding.cweId || "N/A"}
- OWASP: https://owasp.org/

---
Submitted via ScopeHunter`;

  return report;
}

/**
 * Generate Markdown report
 */
export async function generateMarkdownReport(finding: Finding, evidence: string[]): Promise<string> {
  const report = `# ${finding.title}

## Metadata
| Field | Value |
|-------|-------|
| **Type** | ${finding.findingType} |
| **Severity** | ${finding.severity} |
| **CVSS Score** | ${finding.cvssScore} |
| **Status** | ${finding.status} |
| **Discovered** | ${finding.createdAt?.toISOString()} |

## Description
${finding.description || "No description provided"}

## Impact Statement
${finding.impactStatement || "Impact not specified"}

## Reproduction Steps
${finding.reproductionSteps || "Reproduction steps not provided"}

## Affected Assets
${finding.affectedAssets?.map((asset) => `- \`${asset}\``).join("\n") || "- Unknown"}

## Evidence
${evidence.map((e, i) => `### Evidence ${i + 1}\n${e}`).join("\n\n") || "No evidence provided"}

## CVSS v3.1 Score
${finding.cvssScore || "N/A"}/10

## CWE Classification
${finding.cweId ? `CWE-${finding.cweId}` : "Not classified"}

## Remediation
Implement proper security controls to prevent this vulnerability.

---
*Report generated by ScopeHunter on ${new Date().toISOString()}*`;

  return report;
}

/**
 * Generate HTML report with styling
 */
export async function generateHTMLReport(finding: Finding, evidence: string[]): Promise<string> {
  const severityColor: Record<string, string> = {
    critical: "#dc2626",
    high: "#ea580c",
    medium: "#f59e0b",
    low: "#10b981",
    info: "#3b82f6",
  };

  const color = severityColor[finding.severity || "high"] || "#6b7280";

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${finding.title} - Security Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 900px; margin: 0 auto; padding: 40px 20px; }
        header { border-bottom: 3px solid ${color}; padding-bottom: 20px; margin-bottom: 30px; }
        h1 { color: #1f2937; margin-bottom: 10px; }
        .severity { display: inline-block; background: ${color}; color: white; padding: 4px 12px; border-radius: 4px; font-weight: bold; }
        .metadata { background: #f9fafb; border-left: 4px solid ${color}; padding: 15px; margin: 20px 0; border-radius: 4px; }
        .metadata-row { display: flex; justify-content: space-between; padding: 8px 0; }
        .metadata-label { font-weight: bold; color: #6b7280; }
        .section { margin: 30px 0; }
        .section h2 { color: #1f2937; margin-bottom: 15px; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; }
        .section p { margin-bottom: 10px; }
        .code-block { background: #1f2937; color: #e5e7eb; padding: 15px; border-radius: 4px; overflow-x: auto; margin: 10px 0; font-family: 'Courier New', monospace; }
        .evidence { background: #fef3c7; border-left: 4px solid #f59e0b; padding: 15px; margin: 15px 0; border-radius: 4px; }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
        th { background: #f3f4f6; font-weight: bold; }
        footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #6b7280; font-size: 12px; }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>${finding.title}</h1>
            <span class="severity">${finding.severity?.toUpperCase()}</span>
        </header>

        <div class="metadata">
            <div class="metadata-row">
                <span class="metadata-label">Type:</span>
                <span>${finding.findingType}</span>
            </div>
            <div class="metadata-row">
                <span class="metadata-label">CVSS Score:</span>
                <span>${finding.cvssScore}/10</span>
            </div>
            <div class="metadata-row">
                <span class="metadata-label">Status:</span>
                <span>${finding.status}</span>
            </div>
            <div class="metadata-row">
                <span class="metadata-label">Discovered:</span>
                <span>${finding.createdAt?.toISOString()}</span>
            </div>
        </div>

        <div class="section">
            <h2>Description</h2>
            <p>${finding.description || "No description provided"}</p>
        </div>

        <div class="section">
            <h2>Impact</h2>
            <p>${finding.impactStatement || "Impact not specified"}</p>
        </div>

        <div class="section">
            <h2>Reproduction Steps</h2>
            <p>${finding.reproductionSteps || "Reproduction steps not provided"}</p>
        </div>

        <div class="section">
            <h2>Affected Assets</h2>
            <ul>
                ${finding.affectedAssets?.map((asset) => `<li><code>${asset}</code></li>`).join("") || "<li>Unknown</li>"}
            </ul>
        </div>

        ${evidence.length > 0 ? `
        <div class="section">
            <h2>Evidence</h2>
            ${evidence.map((e, i) => `<div class="evidence"><strong>Evidence ${i + 1}:</strong><br><pre>${e}</pre></div>`).join("")}
        </div>
        ` : ""}

        <div class="section">
            <h2>CVSS v3.1 Scoring</h2>
            <p>Score: <strong>${finding.cvssScore}/10</strong></p>
            ${finding.cweId ? `<p>CWE: <strong>CWE-${finding.cweId}</strong></p>` : ""}
        </div>

        <footer>
            <p>Security Report generated by ScopeHunter on ${new Date().toISOString()}</p>
        </footer>
    </div>
</body>
</html>`;

  return html;
}

/**
 * Generate JSON report for API submission
 */
export async function generateJSONReport(finding: Finding, evidence: string[]): Promise<string> {
  const report = {
    vulnerability: {
      id: finding.id,
      title: finding.title,
      type: finding.findingType,
      severity: finding.severity,
      cvssScore: parseFloat(finding.cvssScore || "0"),
      cweId: finding.cweId,
      description: finding.description,
      impactStatement: finding.impactStatement,
      reproductionSteps: finding.reproductionSteps,
      affectedAssets: finding.affectedAssets,
    },
    metadata: {
      status: finding.status,
      discoveredDate: finding.createdAt,
      reportedDate: new Date(),
      tags: finding.tags,
    },
    evidence: evidence,
  };

  return JSON.stringify(report, null, 2);
}

/**
 * Generate vendor disclosure template
 */
export async function generateVendorDisclosureTemplate(finding: Finding): Promise<string> {
  const template = `Subject: Security Vulnerability Disclosure - ${finding.title}

Dear Security Team,

I have discovered a security vulnerability in your application that I believe requires immediate attention.

**Vulnerability Details:**
- Title: ${finding.title}
- Type: ${finding.findingType}
- Severity: ${finding.severity}
- CVSS Score: ${finding.cvssScore}/10

**Description:**
${finding.description || "No description provided"}

**Affected Component(s):**
${finding.affectedAssets?.map((asset) => `- ${asset}`).join("\n") || "- Unknown"}

**Impact:**
${finding.impactStatement || "Impact not specified"}

**Reproduction Steps:**
${finding.reproductionSteps || "Reproduction steps not provided"}

**Timeline:**
- Discovered: ${finding.createdAt?.toISOString()}
- Reported: ${new Date().toISOString()}
- Requested Fix Date: ${new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString()}

I am committed to responsible disclosure and will not publicly disclose this vulnerability until you have had adequate time to address it. I request a 90-day window to allow for patching and deployment.

Please acknowledge receipt of this report and provide updates on your remediation timeline.

Best regards,
Security Researcher

---
This report was generated by ScopeHunter`;

  return template;
}

/**
 * Generate CVE submission template
 */
export async function generateCVETemplate(finding: Finding): Promise<string> {
  const template = `# CVE Submission Request

## Vulnerability Information

**Title:** ${finding.title}

**Description:**
${finding.description || "No description provided"}

**Affected Component(s):**
${finding.affectedAssets?.map((asset) => `- ${asset}`).join("\n") || "- Unknown"}

**Vulnerability Type:**
${finding.findingType}

**Severity:**
${finding.severity} (CVSS v3.1: ${finding.cvssScore}/10)

## Impact

${finding.impactStatement || "Impact not specified"}

## Affected Versions
- [Specify affected versions]

## Proof of Concept
[Include PoC details]

## Timeline
- **Discovery Date:** ${finding.createdAt?.toISOString()}
- **Vendor Notification Date:** ${new Date().toISOString()}
- **Public Disclosure Date:** [To be determined]

## References
- CWE: ${finding.cweId || "N/A"}
- CVSS Calculator: https://www.first.org/cvss/calculator/3.1

---
Generated by ScopeHunter`;

  return template;
}
